[versions]
agp = "8.13.2"
comGoogleDaggerHiltAndroid6 = "2.57.2"
glide = "5.0.5"
hiltNavigationFragment = "1.3.0"
junit = "4.13.2"
junitVersion = "1.1.5"
espressoCore = "3.5.1"
appcompat = "1.6.1"
material = "1.13.0"
recyclerviewIntegration = "4.16.0"
retrofit = "3.0.0"
kotlin = "2.2.0"
coreKtx = "1.17.0"
roomRuntime = "2.8.4"
shimmer = "0.5.0"
swiperefreshlayout = "1.2.0"

[libraries]
androidx-hilt-compiler = { module = "androidx.hilt:hilt-compiler", version.ref = "hiltNavigationFragment" }
androidx-room-compiler = { module = "androidx.room:room-compiler", version.ref = "roomRuntime" }
androidx-room-ktx = { module = "androidx.room:room-ktx", version.ref = "roomRuntime" }
androidx-room-runtime = { module = "androidx.room:room-runtime", version.ref = "roomRuntime" }
androidx-swiperefreshlayout = { module = "androidx.swiperefreshlayout:swiperefreshlayout", version.ref = "swiperefreshlayout" }
com-google-dagger-hilt-android7 = { module = "com.google.dagger:hilt-android", version.ref = "comGoogleDaggerHiltAndroid6" }
compiler = { module = "com.github.bumptech.glide:compiler", version.ref = "glide" }
converter-gson = { module = "com.squareup.retrofit2:converter-gson", version.ref = "retrofit" }
glide = { module = "com.github.bumptech.glide:glide", version.ref = "glide" }
hilt-android-compiler = { module = "com.google.dagger:hilt-android-compiler", version.ref = "comGoogleDaggerHiltAndroid6" }
hilt-android-testing = { module = "com.google.dagger:hilt-android-testing", version.ref = "comGoogleDaggerHiltAndroid6" }
hilt-compiler = { module = "com.google.dagger:hilt-compiler", version.ref = "comGoogleDaggerHiltAndroid6" }
hilt-navigation-fragment = { module = "androidx.hilt:hilt-navigation-fragment", version.ref = "hiltNavigationFragment" }
junit = { group = "junit", name = "junit", version.ref = "junit" }
ext-junit = { group = "androidx.test.ext", name = "junit", version.ref = "junitVersion" }
espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espressoCore" }
appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
material = { module = "com.google.android.material:material", version.ref = "material" }
recyclerview-integration = { module = "com.github.bumptech.glide:recyclerview-integration", version.ref = "glide" }
recyclerview-integration-v4160 = { module = "com.github.bumptech.glide:recyclerview-integration", version.ref = "recyclerviewIntegration" }
retrofit = { module = "com.squareup.retrofit2:retrofit", version.ref = "retrofit" }
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "coreKtx" }
shimmer = { module = "com.facebook.shimmer:shimmer", version.ref = "shimmer" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }

